### ISSUE TITLE
Me déconnecter

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#10]
En tant qu'utilisateur inscrit,
Je veux pouvoir me déconnecter,
Afin que je puisse quitter l'application.

**Comment by lamalice31** [comment]
Given : L’utilisateur est sur l’une des pages de l’application
When : L’utilisateur clique sur le bouton “Se déconnecter” (ou Déconnexion)
Then : L’utilisateur est déconnecté de l’application
