### ISSUE TITLE
Modifier une de mes performances

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#17]
En tant qu'utilisateur connecté,
Je veux pouvoir modifier une de mes performances.

**Comment by lamalice31** [comment]
Given : 
L’utilisateur visualise sa page de performances
When :
L'utilisateur clique sur le bouton "modifier" associé à une performance
L'utilisateur renseigne la nouvelle performance
Then : 
La performance est modifiée
