### ISSUE TITLE
Visualiser les performances d'un utilisateur

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#18]
En tant qu'utilisateur connecté,
Je veux pouvoir visualiser les performances d'un utilisateur.

**Comment by lamalice31** [comment]
Given : 
L’utilisateur est sur la page d'un autre utilisateur "ami"
When :
L'utilisateur clique sur "afficher les performances"
Then : 
Le tableau des performances s'affiche

**Comment by MarjoTiska** [comment]
J'ai intégré l'affichage des graphes et tableaux des performances dans le profil.
Vu que je suis restée sur ma branche, voilà deux screens du résultat :+1: 

![2015-10-31_20h27_25](https://cloud.githubusercontent.com/assets/10879846/10865505/e0b40f78-800d-11e5-8181-d2caf76bad5b.png)
![2015-10-31_20h27_12](https://cloud.githubusercontent.com/assets/10879846/10865506/e1a7c62c-800d-11e5-973d-549ff1ec046d.png)

Si vous avez des propositions, n'hésitez pas. :)
Il manque les tests du controleur et du service. Et je mergerai sur master quand Terry aura merge sa branche sur les performances.
