### ISSUE TITLE
Poster un commentaire dans un événement

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#19]
En tant qu'utilisateur connecté,
Je veux pouvoir poster un commentaire dans un événement,
Afin que je puisse m'exprimer sur celui-ci.

**Comment by lamalice31** [comment]
Given : 
L'utilisateur visualise un événement
When :
L'utilisateur clique sur "ajouter un commentaire"
Then : 
Le commentaire est ajouté à la liste
