### ISSUE TITLE
Rechercher un membre

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#25]
En tant qu'utilisateur connecté,
Je veux pouvoir rechercher un membre,
Afin que je puisse le trouver.

**Comment by MarjoTiska** [comment]
- Given :
 - L’utilisateur est sur la page d’accueil
 - L’utilisateur focus la zone de texte de recherche d’un membre
 - L’utilisateur entre “Sephiroth”
- When :
 - L’utilisateur clique sur “Rechercher”
- Then : Une liste de membres correspondant à sa recherche est affichée

**Comment by RomanianKiwi** [comment]
@MarjoTiska @lamalice31 @clementUps @jak09 Souhaitez-vous que je crée l'action find dans le UserController déjà existant ou préférez-vous que je crée un nouveau contrôleur ?
Pour l'instant, j'ai opté pour la 1ère solution.
:cactus: :camel: :facepunch:

**Comment by RomanianKiwi** [comment]
Après réflexion, je pars sur la solution suivante : 
- création de l'action search dans UserController
- l'action se charge de récupérer la liste des utilisateurs trouvés
- la réponse et le modèle sont redirigés par l'action vers un nouveau contrôleur, chargé de s'occuper de la recherche (ResearchController)

:+1:

**Comment by RomanianKiwi** [comment]
@MarjoTiska @jak09 @lamalice31 @clementUps 
Je m'occupe des vues (formulaire pour effectuer une recherche + page des résultats) ce soir. J'en profiterai aussi pour créer une nouvelle branche (event-search) pour ajouter au contrôleur et aux vues, la recherche des événements.

**Comment by RomanianKiwi** [comment]
Il faut modifier la recherche pour empêcher que la saisie d'une chaîne de caractère vide récupère tous les membres de l'application.
