### ISSUE TITLE
Rechercher un événement

### ISSUE THREAD

**Issue by MarjoTiska** [lamalice31/SwimBook#27]
En tant qu'utilisateur connecté,
Je veux pouvoir rechercher un événement,
Afin que je puisse le trouver.

**Comment by MarjoTiska** [comment]
- Given :
 - L’utilisateur est sur la page d’accueil
 - L’utilisateur focus la zone de texte de recherche d’un évènement
 - L’utilisateur entre “Entraînement”
- When :
 - L’utilisateur clique sur “Rechercher”
- Then : Une liste de évènements correspondant à sa recherche est affichée

**Comment by RomanianKiwi** [comment]
Il faut modifier la recherche pour empêcher que la saisie d'une chaîne de caractère vide récupère tous les événements de l'application.
